### ISSUE TITLE
Readme Update

### ISSUE THREAD

**Issue by Anshul1507** [Anshul1507/animated-portfolio#9]
- [ ] Update 1
```
$ git clone https://github.com/anshul1507/animated-portfolio

This section link needs to be updated to :
$ git clone https://github.com/Anshul1507/animated-portfolio.git
```

- [ ] Update 2
```
Remove '\' from Features part (which is in preview mode)
```

**Comment by crenspact02** [comment]
Hey! Assign this to me, if you may!

**Comment by Anshul1507** [comment]
Sure 👍

**Comment by crenspact02** [comment]
Hey! I've just made the PR. Please check!

**Comment by Anshul1507** [comment]
@crenspact02 are you sure, you done with the changes ? I mean you tested readme file?
As I am unable to see the changes in your forked repo.

If possible, please share the screenshot of updated readme file.
Thanks

**Comment by crenspact02** [comment]
Yes, I did make the changes. Here's the screenshot!
![changes](https://user-images.githubusercontent.com/65359068/94946173-5c7d1080-04f9-11eb-9d8d-c6e86ddd64bf.jpg)

**Comment by Anshul1507** [comment]
I saw the code changed but I was talking about the preview @crenspact02

**Comment by crenspact02** [comment]
Hey check now! The preview has also rendered the edits.

**Comment by Anshul1507** [comment]
This issue is open for contributors now.

**Comment by constant-variable** [comment]
Hey @Anshul1507, Can you please assign me this?

**Comment by Anshul1507** [comment]
Sure, Good to go 👍
